import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/Header";
import localFont from "next/font/local";
import { ClerkProvider } from "@clerk/nextjs";
export const metadata: Metadata = {
  title: "Fincent Online Bookkeepping",
  description: "Generated by create next app",
};
const myFont = localFont({
  src: "../fonts/Celias.otf",
  display: "swap",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link rel="icon" href="/favicon.ico" sizes="any" />
        </head>
        <body className={`antialiased ${myFont.className}`}>
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
